### ISSUE TITLE
can't find phis / topo for ERA5

### ISSUE THREAD

**Issue by JulioTBacmeister** [islasimpson/ERA5interp#1]
We'll need a PHIS or TOPO file for ERA5. Does anyone where to get one? Fortunately we just need one ....

**Comment by islasimpson** [comment]
Oh, I added one yesterday but then I deleted it because it was on the wrong grid.  I thought I pushed the new one but I guess I didn't.  Will do it now

**Comment by JulioTBacmeister** [comment]
Thanks. Where will you/did you put it?

**Comment by islasimpson** [comment]
it's in the ./phis subdirectory

**Comment by JulioTBacmeister** [comment]
Isla, Apologies I still don't see it.  Is it somewhere in /glade/collections/rda/data/ds633.6   Could you send the full path?

**Comment by islasimpson** [comment]
It's in this package.  Here...

https://github.com/islasimpson/ERA5interp/tree/main/phis/

I think if you git pull you should bring it down.  Is that not working?
